# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=320, null=True)),
                ('task_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, choices=[('ToDo', 'ToDo'), ('Doing', 'Doing'), ('Done', 'Done')], max_length=300, null=True)),
                ('priority', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=100, null=True)),
                ('due_date', models.DateField(null=True)),
            ],
        ),
    ]
